name: Build and Test

on:
  push:
    branches-ignore:
      - "no-ci-*"
  pull_request:
    branches:
      - "**"

jobs:
  windows:
    name: Windows memory mapped
    uses: mapnik/mapnik/.github/workflows/windows.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}
  
  windows-mmf-off:
    name: Windows file based
    uses: mapnik/mapnik/.github/workflows/windows.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu:
    name: Linux memory mapped
    uses: mapnik/mapnik/.github/workflows/ubuntu.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu-mmf-off:
    name: Linux file based
    uses: mapnik/mapnik/.github/workflows/ubuntu.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos:
    name: MacOS memory mapped
    uses: mapnik/mapnik/.github/workflows/macos.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos-mmf-off:
    name: MacOS file based
    uses: mapnik/mapnik/.github/workflows/macos.yml@master
    with:
      VCPKG_SHA: 2e34a79a814551424d9b1a981b3b110e0a8fbdfd
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}
