name: Build and Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches-ignore:
      - "no-ci-*"

jobs:
  checkSource:
    name: Check Source Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  windows:
    needs: checkSource
    name: Windows memory mapped
    uses: ./.github/workflows/windows.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "ON"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  windows-mmf-off:
    needs: checkSource
    name: Windows file based
    uses: ./.github/workflows/windows.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "OFF"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu:
    needs: checkSource
    name: Linux memory mapped
    uses: ./.github/workflows/ubuntu.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "ON"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu-mmf-off:
    needs: checkSource
    name: Linux file based
    uses: ./.github/workflows/ubuntu.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "OFF"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos:
    needs: checkSource
    name: MacOS memory mapped
    uses: ./.github/workflows/macos.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "ON"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos-mmf-off:
    needs: checkSource
    name: MacOS file based
    uses: ./.github/workflows/macos.yml
    with:
      VCPKG_SHA: 34d2cf7e62d781f4bcb9c7f44f4d2389f568e92b
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: "OFF"
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}
