name: Build and Test

on:
  push:
    branches-ignore:
      - "no-ci-*"
  pull_request:
    branches:
      - "**"

jobs:
  windows:
    name: Windows memory mapped
    uses: ./.github/workflows/windows.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}
  
  windows-mmf-off:
    name: Windows file based
    uses: ./.github/workflows/windows.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu:
    name: Linux memory mapped
    uses: ./.github/workflows/ubuntu.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  ubuntu-mmf-off:
    name: Linux file based
    uses: ./.github/workflows/ubuntu.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos:
    name: MacOS memory mapped
    uses: ./.github/workflows/macos.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'ON'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}

  macos-mmf-off:
    name: MacOS file based
    uses: ./.github/workflows/macos.yml
    with:
      VCPKG_SHA: 4415a0f31b5a012ca2efba13cc18e16adefd89c0
      NUGET_REGISTRY: https://nuget.pkg.github.com/mapnik/index.json
      NUGET_USERNAME: mapnik
      USE_MEMORY_MAPPED_FILE: 'OFF'
    secrets:
      NUGET_REGISTRY_PAT: ${{ secrets.VCPKG_CACHE_PAT }}
